version: '3'
services:
    www:        
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/      
    db:
        image: mysql:latest   
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: local
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123       
        volumes:
            - ./data:/var/lib/mysql
            - ./myDb:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: 'db'
            MYSQL_ROOT_PASSWORD: 123
volumes:
    persistent: